### Register a new user
POST https://localhost:8000/api/register
Content-Type: application/json

{
    "email" : "fabian@derschatta.de",
    "first_name" : "Fabian",
    "last_name" : "Derschatta",
    "password" : "12345.Fab#$ian"
}
###
### Log user in
POST https://localhost:8000/api/login_check
Content-Type: application/json

{
    "username": "fabian@derschatta.de",
    "password" : "12345.Fab#$ian"
}
###
### Get all users
GET https://localhost:8000/api/users
Authorization: Bearer [token]
###
### Get current users
GET https://localhost:8000/api/user/me
Authorization: Bearer [token]
###
