
services:
  php:
    image: dunglas/frankenphp
    build:
      context: docker/php
#    restart: always
    ports:
      - "80:80" # HTTP
      - "8000:443" # HTTPS
#      - "443:443/udp" # HTTP/3
#    environment:
#      CADDY_SERVER_EXTRA_DIRECTIVES: "tls /etc/app/certs/localhost.pem /etc/app/certs/localhost-key.pem"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - .:/app
      - ./docker/php/certs:/etc/app/certs
    tty: true

  database:
    image: mysql:8.4
#    restart: always
    environment:
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "!ChangeMe!"
      MYSQL_DATABASE: "app"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
       - ./docker/db/data:/var/lib/mysql:rw
    tty: true

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411
      -
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9412
    ports:
      - 9412:9412
      - 16686:16686

volumes:
  database_data:
  caddy_data:
  caddy_config:
